services:
  postgres:
    image: postgres:15
    container_name: recetas_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: recetas
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
